customhost = "project2database.c9fcbifcfonc.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "project2database"
custombucket = "project2bucket12"
customregion = "us-east-1"
